name: Release on tag

on:
  push:
    tags:
      - 'v*'         # ex: v2.0.73, v2.0.73-rc.1

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write   # créer/mettre à jour la Release + pousser le changelog

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'    # ⚠️ pas de cache ici

      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then
            echo "Using npm ci (lockfile found)"
            npm ci
          else
            echo "No lockfile found → using npm install"
            npm install --no-fund --no-audit
          fi

      - name: Compile
        run: npx hardhat compile

      # (Optionnel) Génère un changelog simple à partir des commits
      - name: Generate CHANGELOG.md
        run: |
          npx -y conventional-changelog-cli -p angular -i CHANGELOG.md -s || echo "changelog step skipped"
          git add CHANGELOG.md || true
