name: Static Analysis — Slither

on:
  pull_request:
  push:
    branches: [ "main", "dev" ]

permissions:
  contents: read

jobs:
  slither:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          # remove cache: 'npm' since there is no package-lock.json

      - name: Install deps
        run: npm install --no-audit --no-fund

      - name: Run Slither
        uses: crytic/slither-action@v0.3.0
        with:
          target: .
          solc-version: 0.8.24
          fail-on: high
          sarif: true
          slither-args: --filter-paths "node_modules"
